Move VNC to common script place and guard w/ env var

diff --git a/devtools/node/setup_frontend_deps b/devtools/node/setup_frontend_deps
--- a/devtools/node/setup_frontend_deps
+++ b/devtools/node/setup_frontend_deps
@@ -19,3 +19,16 @@ if [ $? -ne 0 ]; then
 fi
 
 npm run test-selenium-install
+
+
+if [[ -z "${START_VNC}" ]]; then
+  echo "Not starting VNC"
+else
+  # in the case of wait, we will want to setup the VNC.
+  /dockerstartup/vnc_startup.sh
+  if [ $? -ne 0 ]; then
+    # if it fails, we should exit before getting caught in the sleep command.
+    echo "something went wrong setting up vnc"
+    exit 1
+  fi
+fi
